name: Docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: 3.12
          architecture: x64
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Build
        run: mkdocs build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: site
          path: site/*
          if-no-files-found: error
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
    - build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        ref: gh-pages
        path: dist
        ssh-key: ${{secrets.WEBSITE_DEPLOY_KEY}}
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
      with:
        name: site
        path: artifacts
    - name: Deploy
      run: |
        set -euo pipefail
        rsync -az --exclude=.git --delete ./artifacts/ ./dist/
        cd dist
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Docs update"
          git push --set-upstream --force origin gh-pages
        fi

